import type {
  AdminReview,
  AdminModerationCrmData,
  AuditLogEntry,
  BulkImportBatch,
  ClientIntakeAssessment,
  ClientProfile,
  ClientReport,
  ClientResponse,
  ContractorActivityItem,
  CommunityDiscussion,
  ContractorRiskOpsData,
  ContractorWatchlistItem,
  ContractorProfile,
  EvidenceReviewSummary,
  ModerationCase,
  ReportDraft,
  ReportEvidence,
  SavedSearch,
  Subscription,
  User,
  WatchlistAlert,
} from "@/lib/types"

export const users: User[] = [
  {
    id: "user_contractor_01",
    email: "morgan@ridgebuild.com",
    fullName: "Morgan Ellis",
    role: "contractor",
    createdAt: "2026-02-02T14:00:00.000Z",
  },
  {
    id: "user_admin_01",
    email: "review@clientbureau.com",
    fullName: "Client Bureau Review Team",
    role: "admin",
    createdAt: "2026-01-12T14:00:00.000Z",
  },
]

export const contractorProfiles: ContractorProfile[] = [
  {
    id: "contractor_01",
    userId: "user_contractor_01",
    businessName: "RidgeBuild Contracting",
    trade: "Residential remodeling",
    city: "Orlando",
    state: "FL",
    licenseNumber: "FL-CBC-49201",
    verificationStatus: "pending",
    verificationBadges: ["Verified business", "Verified email", "Verified phone"],
    createdAt: "2026-02-03T14:00:00.000Z",
  },
]

export const clientProfiles: ClientProfile[] = [
  {
    id: "client_01",
    firstName: "John",
    lastName: "Smith",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    phoneHash: "sha256:79a40d12d7c37e3f1b-private",
    emailHash: "sha256:2df0cb6b9e763a17-private",
    publicSlug: "john-smith-orlando-fl",
    clientBureauScore: 48,
    riskLevel: "Elevated",
    reportCount: 2,
    createdAt: "2026-03-04T15:20:00.000Z",
    updatedAt: "2026-05-20T12:30:00.000Z",
    isPublic: true,
  },
  {
    id: "client_02",
    firstName: "Maria",
    lastName: "Alvarez",
    businessName: "Alvarez Beach Rentals",
    city: "Tampa",
    state: "FL",
    zip: "33602",
    phoneHash: "sha256:4bf10de74a31fba10-private",
    emailHash: "sha256:8b4e2b190f60ac99-private",
    publicSlug: "maria-alvarez-tampa-fl",
    clientBureauScore: 86,
    riskLevel: "Low",
    reportCount: 2,
    createdAt: "2026-02-12T11:20:00.000Z",
    updatedAt: "2026-05-18T09:16:00.000Z",
    isPublic: true,
  },
  {
    id: "client_03",
    firstName: "Daniel",
    lastName: "Reed",
    businessName: "Reed Family Trust",
    city: "Austin",
    state: "TX",
    zip: "78701",
    phoneHash: "sha256:99a39d8c3f318b74-private",
    emailHash: "sha256:7751ac2c901ef431-private",
    publicSlug: "daniel-reed-austin-tx",
    clientBureauScore: 39,
    riskLevel: "High",
    reportCount: 2,
    createdAt: "2026-01-29T18:10:00.000Z",
    updatedAt: "2026-05-09T13:40:00.000Z",
    isPublic: true,
  },
  {
    id: "client_04",
    firstName: "Elaine",
    lastName: "Parker",
    city: "Nashville",
    state: "TN",
    phoneHash: "sha256:pending-phone-private",
    emailHash: "sha256:pending-email-private",
    publicSlug: "elaine-parker-nashville-tn",
    clientBureauScore: 78,
    riskLevel: "Moderate",
    reportCount: 0,
    createdAt: "2026-05-22T10:00:00.000Z",
    updatedAt: "2026-05-22T10:00:00.000Z",
    isPublic: false,
  },
]

export const clientReports: ClientReport[] = [
  {
    id: "report_01",
    contractorId: "contractor_01",
    clientId: "client_01",
    projectType: "Kitchen remodel",
    projectCity: "Orlando",
    projectState: "FL",
    contractAmount: 18400,
    amountUnpaid: 4200,
    reportCategory: "Non-payment",
    paymentStatus: "Final invoice partially unpaid",
    reportSummary: "Contractor-submitted report says the final invoice remained partially unpaid after documented completion.",
    detailedExperience:
      "The contractor reported that punch-list items were completed, photos were shared, and the client acknowledged the remaining balance before communication slowed.",
    publicSummary:
      "A contractor-submitted report states that a final invoice remained partially unpaid after documented completion of a kitchen remodel.",
    evidenceAttached: true,
    status: "approved",
    resolutionStatus: "Unresolved",
    moderationNote: "Published summary is limited to documented timeline and payment status.",
    createdAt: "2026-04-08T14:31:00.000Z",
    approvedAt: "2026-04-12T16:45:00.000Z",
  },
  {
    id: "report_02",
    contractorId: "contractor_01",
    clientId: "client_01",
    projectType: "Bathroom repair",
    projectCity: "Orlando",
    projectState: "FL",
    contractAmount: 6200,
    amountUnpaid: 0,
    reportCategory: "Scope creep",
    paymentStatus: "Paid after revised invoice",
    reportSummary: "Contractor reported multiple unpaid change requests before final payment was made.",
    detailedExperience:
      "The contractor reported several requests beyond the original agreement. A revised invoice was eventually paid after documentation was exchanged.",
    publicSummary:
      "A contractor-submitted report describes multiple change requests outside the original scope before payment was resolved.",
    evidenceAttached: true,
    status: "approved",
    resolutionStatus: "Resolved",
    moderationNote: "Approved as a reported experience with payment resolved.",
    createdAt: "2026-03-06T09:10:00.000Z",
    approvedAt: "2026-03-10T11:40:00.000Z",
  },
  {
    id: "report_03",
    contractorId: "contractor_01",
    clientId: "client_02",
    projectType: "Rental unit paint refresh",
    projectCity: "Tampa",
    projectState: "FL",
    contractAmount: 5100,
    amountUnpaid: 0,
    reportCategory: "Positive experience",
    paymentStatus: "Paid on schedule",
    reportSummary: "Contractor reported prompt approvals and payment on schedule.",
    detailedExperience:
      "The contractor reported clear communication, timely access to the unit, and payment within the agreed invoice window.",
    publicSummary:
      "A contractor-submitted report describes clear communication and payment within the agreed invoice window.",
    evidenceAttached: false,
    status: "approved",
    resolutionStatus: "Paid in full",
    createdAt: "2026-05-01T12:00:00.000Z",
    approvedAt: "2026-05-02T17:00:00.000Z",
  },
  {
    id: "report_04",
    contractorId: "contractor_01",
    clientId: "client_02",
    projectType: "Deck maintenance",
    projectCity: "Tampa",
    projectState: "FL",
    contractAmount: 3900,
    amountUnpaid: 0,
    reportCategory: "Would work with again",
    paymentStatus: "Paid early",
    reportSummary: "Contractor reported an organized project and early payment.",
    detailedExperience:
      "The contractor reported that project decisions were made quickly and the invoice was paid before the due date.",
    publicSummary:
      "A contractor-submitted report says the project was organized and the invoice was paid before the due date.",
    evidenceAttached: false,
    status: "approved",
    resolutionStatus: "Paid in full",
    createdAt: "2026-05-08T15:00:00.000Z",
    approvedAt: "2026-05-10T17:00:00.000Z",
  },
  {
    id: "report_05",
    contractorId: "contractor_01",
    clientId: "client_03",
    projectType: "Pool enclosure",
    projectCity: "Austin",
    projectState: "TX",
    contractAmount: 28600,
    amountUnpaid: 9600,
    reportCategory: "Chargeback",
    paymentStatus: "Chargeback opened after completion",
    reportSummary: "Contractor-submitted report states a chargeback was opened after completion documents were delivered.",
    detailedExperience:
      "The contractor reported that completion photos, signed approvals, and invoice records were provided before a payment reversal was opened.",
    publicSummary:
      "A contractor-submitted report states that a payment reversal was opened after completion documents were delivered.",
    evidenceAttached: true,
    status: "approved",
    resolutionStatus: "Unresolved",
    moderationNote: "Public summary avoids intent claims and names only the reported payment event.",
    createdAt: "2026-02-11T16:45:00.000Z",
    approvedAt: "2026-02-15T10:20:00.000Z",
  },
  {
    id: "report_06",
    contractorId: "contractor_01",
    clientId: "client_03",
    projectType: "Fence repair",
    projectCity: "Austin",
    projectState: "TX",
    contractAmount: 7400,
    amountUnpaid: 2100,
    reportCategory: "Late payment",
    paymentStatus: "Paid after collection notice",
    reportSummary: "Contractor reported payment after multiple notices and a documented delay.",
    detailedExperience:
      "The contractor reported that payment arrived after several notices and after the invoice had moved beyond the original terms.",
    publicSummary:
      "A contractor-submitted report says payment was received after multiple notices and a documented delay.",
    evidenceAttached: true,
    status: "disputed",
    resolutionStatus: "Disputed",
    moderationNote: "Published with active dispute flag and right-of-response link.",
    createdAt: "2026-04-01T11:05:00.000Z",
  },
  {
    id: "report_07",
    contractorId: "contractor_01",
    clientId: "client_04",
    projectType: "Exterior repair",
    projectCity: "Nashville",
    projectState: "TN",
    contractAmount: 11800,
    amountUnpaid: 3200,
    reportCategory: "No-show / cancellation",
    paymentStatus: "Deposit retained per agreement",
    reportSummary: "Contractor reported repeated access cancellations before work could begin.",
    detailedExperience:
      "The contractor reported several scheduled access windows were missed, creating crew and material costs.",
    publicSummary:
      "A contractor-submitted report describes repeated access cancellations before work could begin.",
    evidenceAttached: true,
    status: "pending",
    resolutionStatus: "Unresolved",
    createdAt: "2026-05-22T10:00:00.000Z",
  },
]

export const reportEvidence: ReportEvidence[] = [
  {
    id: "evidence_01",
    reportId: "report_01",
    fileName: "signed-completion-form.pdf",
    fileType: "application/pdf",
    storagePath: "report-evidence/report_01/signed-completion-form.pdf",
    uploadedAt: "2026-04-08T14:36:00.000Z",
  },
  {
    id: "evidence_02",
    reportId: "report_01",
    fileName: "final-invoice.pdf",
    fileType: "application/pdf",
    storagePath: "report-evidence/report_01/final-invoice.pdf",
    uploadedAt: "2026-04-08T14:37:00.000Z",
  },
  {
    id: "evidence_03",
    reportId: "report_05",
    fileName: "chargeback-notice.png",
    fileType: "image/png",
    storagePath: "report-evidence/report_05/chargeback-notice.png",
    uploadedAt: "2026-02-11T16:50:00.000Z",
  },
  {
    id: "evidence_04",
    reportId: "report_07",
    fileName: "access-window-log.pdf",
    fileType: "application/pdf",
    storagePath: "report-evidence/report_07/access-window-log.pdf",
    uploadedAt: "2026-05-22T10:05:00.000Z",
  },
]

export const clientResponses: ClientResponse[] = [
  {
    id: "response_01",
    clientId: "client_03",
    reportId: "report_06",
    responseSummary:
      "The client response says final payment timing was connected to a requested documentation review. Client Bureau has marked the report as disputed while review continues.",
    status: "published",
    createdAt: "2026-04-05T12:10:00.000Z",
    publishedAt: "2026-04-06T14:10:00.000Z",
  },
]

export const communityDiscussions: CommunityDiscussion[] = [
  {
    id: "discussion_01",
    clientId: "client_01",
    reportId: "report_01",
    authorName: "Verified Orlando Remodeler",
    authorEmailHash: "sha256:discussion-email-private-01",
    relationshipCategory: "Contractor Experience",
    commentBody:
      "A contractor-submitted discussion entry says invoice and completion records were reviewed before this profile was published.",
    status: "approved",
    isVerified: true,
    moderatorNote: "Approved as supporting context without exposing private identifiers.",
    createdAt: "2026-05-20T16:25:00.000Z",
    updatedAt: "2026-05-20T17:10:00.000Z",
    publishedAt: "2026-05-20T17:10:00.000Z",
  },
  {
    id: "discussion_02",
    clientId: "client_03",
    reportId: "report_06",
    authorName: "Client response contact",
    authorEmailHash: "sha256:discussion-email-private-02",
    relationshipCategory: "Dispute / Correction",
    commentBody:
      "A response contact submitted additional timing context for the disputed fence repair report.",
    status: "pending",
    isVerified: false,
    createdAt: "2026-05-28T12:15:00.000Z",
    updatedAt: "2026-05-28T12:15:00.000Z",
  },
]

export const subscriptions: Subscription[] = [
  {
    id: "sub_01",
    contractorId: "contractor_01",
    tier: "pro",
    status: "mock",
    stripeCustomerId: "cus_mock_ridgebuild",
    stripeSubscriptionId: "sub_mock_pro",
    stripePriceId: "price_mock_pro_monthly",
    currentPeriodEnd: "2026-06-30T00:00:00.000Z",
  },
]

export const adminReviews: AdminReview[] = [
  {
    id: "review_01",
    reportId: "report_07",
    status: "queued",
    notes: "Check evidence names, contract timeline, and neutral summary before publishing.",
    createdAt: "2026-05-22T10:06:00.000Z",
    updatedAt: "2026-05-22T10:06:00.000Z",
  },
  {
    id: "review_02",
    reportId: "report_06",
    status: "needs_dispute_review",
    reviewerId: "user_admin_01",
    notes: "Client response received. Keep profile public and show active dispute context.",
    createdAt: "2026-04-05T12:30:00.000Z",
    updatedAt: "2026-04-06T14:15:00.000Z",
  },
]

export const auditLogs: AuditLogEntry[] = [
  {
    id: "audit_01",
    actorId: "user_admin_01",
    actorName: "Client Bureau Review Team",
    action: "approved_report",
    entityType: "report",
    entityId: "report_01",
    summary: "Approved public summary and published client profile.",
    metadata: { publicSlug: "john-smith-orlando-fl" },
    createdAt: "2026-04-12T16:45:00.000Z",
  },
  {
    id: "audit_02",
    actorId: "user_admin_01",
    actorName: "Client Bureau Review Team",
    action: "queued_discussion",
    entityType: "discussion",
    entityId: "discussion_02",
    summary: "Community discussion entry queued for moderation.",
    createdAt: "2026-05-28T12:15:00.000Z",
  },
]

export const savedSearches: SavedSearch[] = [
  {
    id: "search_01",
    contractorId: "contractor_01",
    query: "John Smith Orlando FL",
    city: "Orlando",
    state: "FL",
    createdAt: "2026-05-20T16:00:00.000Z",
  },
  {
    id: "search_02",
    contractorId: "contractor_01",
    query: "Tampa rental owner",
    city: "Tampa",
    state: "FL",
    createdAt: "2026-05-19T14:00:00.000Z",
  },
]

export const contractorWatchlist: ContractorWatchlistItem[] = [
  {
    id: "watch_01",
    contractorId: "contractor_01",
    clientId: "client_01",
    status: "active",
    watchReason: "Review before accepting additional change-order work.",
    alertLevel: "high",
    lastSignal: "New discussion context and unresolved payment history require intake review.",
    privateMatch: true,
    createdAt: "2026-05-20T17:30:00.000Z",
    updatedAt: "2026-05-29T13:10:00.000Z",
  },
  {
    id: "watch_02",
    contractorId: "contractor_01",
    clientId: "client_03",
    status: "active",
    watchReason: "Require documented payment milestones before scheduling crews.",
    alertLevel: "urgent",
    lastSignal: "Active dispute context is attached to one report.",
    privateMatch: false,
    createdAt: "2026-05-14T12:00:00.000Z",
    updatedAt: "2026-05-28T15:45:00.000Z",
  },
]

export const watchlistAlerts: WatchlistAlert[] = [
  {
    id: "alert_01",
    contractorId: "contractor_01",
    clientId: "client_01",
    profileSlug: "john-smith-orlando-fl",
    eventType: "payment_status_changed",
    title: "Reported unpaid balance still unresolved",
    description: "A watched Orlando profile still shows an unresolved reported balance before additional work is accepted.",
    severity: "high",
    createdAt: "2026-05-31T10:00:00.000Z",
  },
  {
    id: "alert_02",
    contractorId: "contractor_01",
    clientId: "client_03",
    profileSlug: "daniel-reed-austin-tx",
    eventType: "dispute_opened",
    title: "Dispute context attached",
    description: "A watched profile has active response or dispute context. Review the public summary before scheduling.",
    severity: "urgent",
    createdAt: "2026-05-30T14:20:00.000Z",
  },
  {
    id: "alert_03",
    contractorId: "contractor_01",
    clientId: "client_02",
    profileSlug: "maria-alvarez-tampa-fl",
    eventType: "case_resolved",
    title: "Positive payment context available",
    description: "A watched Tampa profile includes positive reports and paid-in-full context.",
    severity: "normal",
    createdAt: "2026-05-28T09:30:00.000Z",
    readAt: "2026-05-29T09:30:00.000Z",
  },
]

export const reportDrafts: ReportDraft[] = [
  {
    id: "draft_01",
    contractorId: "contractor_01",
    clientId: "client_04",
    clientName: "Elaine Parker",
    projectType: "Exterior repair",
    estimatedValue: 11800,
    amountAtRisk: 3200,
    summary: "Draft contains project access timeline and deposit context.",
    nextStep: "Attach access-window documentation before submission.",
    status: "ready_to_submit",
    updatedAt: "2026-05-29T16:20:00.000Z",
  },
  {
    id: "draft_02",
    contractorId: "contractor_01",
    clientName: "New intake client",
    projectType: "Roof repair",
    estimatedValue: 16400,
    amountAtRisk: 0,
    summary: "Draft started from intake assessment and needs payment timeline detail.",
    nextStep: "Add invoice terms and communication timeline.",
    status: "draft",
    updatedAt: "2026-05-30T11:05:00.000Z",
  },
]

export const intakeAssessments: ClientIntakeAssessment[] = [
  {
    id: "intake_01",
    contractorId: "contractor_01",
    clientName: "John Smith",
    city: "Orlando",
    state: "FL",
    projectValue: 9400,
    depositReceived: false,
    contractSigned: false,
    privateMatchConfirmed: true,
    recommendation: "Use milestone billing",
    score: 62,
    notes: "Private match found approved report context. Require milestone language before scheduling.",
    createdAt: "2026-05-30T12:45:00.000Z",
  },
  {
    id: "intake_02",
    contractorId: "contractor_01",
    clientName: "Maria Alvarez",
    city: "Tampa",
    state: "FL",
    projectValue: 5200,
    depositReceived: true,
    contractSigned: true,
    privateMatchConfirmed: true,
    recommendation: "Proceed",
    score: 91,
    notes: "Positive report history and clear project controls are present.",
    createdAt: "2026-05-28T09:30:00.000Z",
  },
]

export const evidenceReviewSummaries: EvidenceReviewSummary[] = [
  {
    id: "evidence_summary_01",
    contractorId: "contractor_01",
    reportId: "report_01",
    status: "reviewed",
    label: "Invoices and completion records reviewed privately.",
    fileCount: 2,
    reviewedCount: 2,
    lastUpdatedAt: "2026-05-28T15:00:00.000Z",
  },
  {
    id: "evidence_summary_02",
    contractorId: "contractor_01",
    reportId: "report_07",
    status: "review_pending",
    label: "Access-window documentation queued for review.",
    fileCount: 1,
    reviewedCount: 0,
    lastUpdatedAt: "2026-05-29T10:10:00.000Z",
  },
]

export const contractorActivity: ContractorActivityItem[] = [
  {
    id: "activity_01",
    contractorId: "contractor_01",
    title: "Report queued for moderation",
    description: "Exterior repair report is waiting for evidence review.",
    createdAt: "2026-05-29T10:10:00.000Z",
    tone: "warning",
  },
  {
    id: "activity_02",
    contractorId: "contractor_01",
    title: "Profile search saved",
    description: "Orlando client intake search was saved for later review.",
    createdAt: "2026-05-28T13:15:00.000Z",
    tone: "neutral",
  },
  {
    id: "activity_03",
    contractorId: "contractor_01",
    title: "Positive report approved",
    description: "Tampa rental owner report is published as positive context.",
    createdAt: "2026-05-10T17:00:00.000Z",
    tone: "positive",
  },
]

export const moderationCases: ModerationCase[] = [
  {
    id: "case_01",
    reportId: "report_07",
    clientId: "client_04",
    title: "Elaine Parker exterior repair",
    summary: "Pending report with access-window evidence and deposit context.",
    priority: "high",
    status: "unassigned",
    queueStage: "evidence_review",
    dueAt: "2026-06-03T16:00:00.000Z",
    publicSummaryPreview:
      "A contractor-submitted report describes repeated access cancellations before work could begin.",
    createdAt: "2026-05-22T10:06:00.000Z",
    updatedAt: "2026-05-30T12:00:00.000Z",
  },
  {
    id: "case_02",
    reportId: "report_06",
    discussionId: "discussion_02",
    clientId: "client_03",
    title: "Daniel Reed dispute review",
    summary: "Client response contact submitted timing context for a disputed report.",
    priority: "urgent",
    status: "escalated",
    queueStage: "decision",
    assignedTo: "user_admin_01",
    assignedToName: "Client Bureau Review Team",
    dueAt: "2026-06-02T18:00:00.000Z",
    decisionReason: "approved_with_edits",
    escalationNote: "Keep response context visible and avoid conclusory wording.",
    publicSummaryPreview:
      "A contractor-submitted report says payment was received after multiple notices and a documented delay.",
    createdAt: "2026-04-05T12:30:00.000Z",
    updatedAt: "2026-05-31T14:20:00.000Z",
  },
  {
    id: "case_03",
    discussionId: "discussion_02",
    clientId: "client_03",
    title: "Community discussion verification",
    summary: "Supporting context requires contact verification before public display.",
    priority: "normal",
    status: "assigned",
    queueStage: "triage",
    assignedTo: "user_admin_01",
    assignedToName: "Client Bureau Review Team",
    dueAt: "2026-06-05T14:00:00.000Z",
    createdAt: "2026-05-28T12:15:00.000Z",
    updatedAt: "2026-05-28T12:15:00.000Z",
  },
]

export const adminWorkloadMetrics: AdminModerationCrmData["workload"] = [
  {
    id: "workload_01",
    label: "Aging cases",
    value: 2,
    helper: "Due within the next 48 hours",
    tone: "amber",
  },
  {
    id: "workload_02",
    label: "Escalations",
    value: 1,
    helper: "Requires senior moderation review",
    tone: "rose",
  },
  {
    id: "workload_03",
    label: "Assigned",
    value: 2,
    helper: "Owned by current review team",
    tone: "slate",
  },
  {
    id: "workload_04",
    label: "Closed today",
    value: 3,
    helper: "Reports, discussions, and profile edits",
    tone: "emerald",
  },
]

export const bulkImportBatches: BulkImportBatch[] = [
  {
    id: "batch_01",
    fileName: "orlando-ar-aging.csv",
    createdBy: "Client Bureau Review Team",
    createdAt: "2026-05-30T13:10:00.000Z",
    totalRows: 42,
    readyRows: 31,
    duplicateRows: 6,
    importedRows: 24,
    status: "needs_review",
  },
  {
    id: "batch_02",
    fileName: "tampa-positive-context.csv",
    createdBy: "Client Bureau Review Team",
    createdAt: "2026-05-26T10:00:00.000Z",
    totalRows: 18,
    readyRows: 18,
    duplicateRows: 0,
    importedRows: 18,
    status: "imported",
  },
]

export const contractorRiskOps: ContractorRiskOpsData = {
  watchlist: contractorWatchlist,
  watchlistAlerts,
  reportDrafts,
  intakeAssessments,
  evidenceSummaries: evidenceReviewSummaries,
  activity: contractorActivity,
  recommendedActions: [
    "Review high-priority watchlist entries before scheduling new work.",
    "Attach evidence to ready report drafts before submitting.",
    "Use milestone billing when private match context indicates reported payment risk.",
  ],
}

export const adminModerationCrm: AdminModerationCrmData = {
  cases: moderationCases,
  workload: adminWorkloadMetrics,
  importBatches: bulkImportBatches,
}
